fix: unbreak dependencies
We were getting this error when running unpage:

```
...
TypeError: cannot specify both default and default_factory
```

The `--prerelease allow` was getting pydantic version 2.12.0a1, which blows up because FastMCP has an object that sets both a default and a default_factory:

```python
    server_dependencies: Annotated[
        list[str],
        Field(
            default_factory=list,
            description="List of dependencies to install in the server environment",
        ),
    ] = []
```
from: https://github.com/jlowin/fastmcp/blob/3fc96c6fd5324f757430a0fef4a7f1cef0cb1c56/src/fastmcp/settings.py#L247-L253

Adding a constraint to pydantic to keep it below 2.12 fixes the issue.

...now we'll just need to figure out how we ask users to run unpage...